In [2]:
#PartA
import numpy as np

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

from keras.layers import Dense, Activation
from keras.models import Sequential
from keras.utils import np_utils


In [3]:
#PartB
from keras.datasets import mnist
(X_train, y_train), (X_test, Y_test) = mnist.load_data()
X_train = X_train.reshape(X_train.shape[0], 784)
X_test = X_test.reshape(X_test.shape[0], 784)
print(X_train.shape)
print (X_test.shape)

(60000, 784)
(10000, 784)


In [4]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255



In [6]:
#PartC
y_train = np_utils.to_categorical(y_train, 10)
Y_test = np_utils.to_categorical(Y_test, 10)

In [7]:
print (y_train.shape)
print (y_train[:10,:])

(60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [8]:
#PartD
input_size = 784
hidden_neurons = 100
out_size = 10
def model_creator():
    model = Sequential()
    model.add(Dense(hidden_neurons, input_dim=input_size))
    model.add(Activation('sigmoid'))
    
    model.add(Dense(out_size, input_dim=hidden_neurons))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics = ['accuracy'])
    return model


In [9]:
#PartE
seed = 2
np.random.seed(2)


In [10]:
#PartF
model = KerasClassifier(build_fn=model_creator, verbose = 2)



In [11]:
#PartG
epochs = np.array([10, 15, 20])
batch_size = np.array([30, 50, 100])
param_grid = dict(epochs = epochs, batch_size = batch_size)
grid = GridSearchCV(estimator=model, param_grid=param_grid, scoring='neg_log_loss', cv=10)

In [12]:
grid_result = grid.fit(X_train, y_train, verbose = 1)

Epoch 1/10
54000/54000 [==============================] - 6s 118us/step - loss: 0.4333 - accuracy: 0.8898
Epoch 2/10
54000/54000 [==============================] - 6s 111us/step - loss: 0.2095 - accuracy: 0.9400
Epoch 3/10
54000/54000 [==============================] - 6s 108us/step - loss: 0.1572 - accuracy: 0.9544
Epoch 4/10
54000/54000 [==============================] - 6s 115us/step - loss: 0.1236 - accuracy: 0.9642
Epoch 5/10
54000/54000 [==============================] - 6s 104us/step - loss: 0.0996 - accuracy: 0.97160s - loss: 0.0999 - accuracy: 
Epoch 6/10
54000/54000 [==============================] - 6s 108us/step - loss: 0.0827 - accuracy: 0.9769
Epoch 7/10
54000/54000 [==============================] - 6s 112us/step - loss: 0.0696 - accuracy: 0.9803
Epoch 8/10
54000/54000 [==============================] - 6s 110us/step - loss: 0.0593 - accuracy: 0.9841
Epoch 9/10
54000/54000 [==============================] - 6s 108us/step - loss: 0.0510 - accuracy: 0.9861
Epoch 10/10
5400

54000/54000 [==============================] - 5s 91us/step - loss: 0.0718 - accuracy: 0.9798
Epoch 8/10
54000/54000 [==============================] - 5s 95us/step - loss: 0.0616 - accuracy: 0.9828
Epoch 9/10
54000/54000 [==============================] - 5s 91us/step - loss: 0.0531 - accuracy: 0.9855
Epoch 10/10
54000/54000 [==============================] - 5s 91us/step - loss: 0.0460 - accuracy: 0.9877
Epoch 1/10
54000/54000 [==============================] - 5s 87us/step - loss: 0.4320 - accuracy: 0.8896
Epoch 2/10
54000/54000 [==============================] - 5s 84us/step - loss: 0.2081 - accuracy: 0.9406
Epoch 3/10
54000/54000 [==============================] - 5s 84us/step - loss: 0.1563 - accuracy: 0.9547
Epoch 4/10
54000/54000 [==============================] - 5s 84us/step - loss: 0.1242 - accuracy: 0.9641
Epoch 5/10
54000/54000 [==============================] - 5s 84us/step - loss: 0.1009 - accuracy: 0.9715
Epoch 6/10
54000/54000 [==============================] - 5s 84us

54000/54000 [==============================] - 5s 86us/step - loss: 0.0715 - accuracy: 0.9800
Epoch 8/15
54000/54000 [==============================] - 5s 84us/step - loss: 0.0606 - accuracy: 0.9833
Epoch 9/15
54000/54000 [==============================] - 5s 84us/step - loss: 0.0519 - accuracy: 0.9858
Epoch 10/15
54000/54000 [==============================] - 5s 84us/step - loss: 0.0451 - accuracy: 0.9879
Epoch 11/15
54000/54000 [==============================] - 5s 84us/step - loss: 0.0385 - accuracy: 0.9904 0s - loss: 0.0386 - accura
Epoch 12/15
54000/54000 [==============================] - 5s 84us/step - loss: 0.0331 - accuracy: 0.9921 0s
Epoch 13/15
54000/54000 [==============================] - 5s 84us/step - loss: 0.0288 - accuracy: 0.9932
Epoch 14/15
54000/54000 [==============================] - 5s 85us/step - loss: 0.0248 - accuracy: 0.9944
Epoch 15/15
54000/54000 [==============================] - 5s 84us/step - loss: 0.0209 - accuracy: 0.9959
Epoch 1/15
54000/54000 [======

54000/54000 [==============================] - 5s 87us/step - loss: 0.0623 - accuracy: 0.9830
Epoch 9/15
54000/54000 [==============================] - 5s 87us/step - loss: 0.0534 - accuracy: 0.9857
Epoch 10/15
54000/54000 [==============================] - 5s 87us/step - loss: 0.0462 - accuracy: 0.9877
Epoch 11/15
54000/54000 [==============================] - 5s 87us/step - loss: 0.0399 - accuracy: 0.9896
Epoch 12/15
54000/54000 [==============================] - 5s 90us/step - loss: 0.0346 - accuracy: 0.9911
Epoch 13/15
54000/54000 [==============================] - 5s 86us/step - loss: 0.0299 - accuracy: 0.9931
Epoch 14/15
54000/54000 [==============================] - 5s 86us/step - loss: 0.0255 - accuracy: 0.9946 0s - loss: 0.0255 - accuracy
Epoch 15/15
54000/54000 [==============================] - 5s 86us/step - loss: 0.0222 - accuracy: 0.9957
Epoch 1/15
54000/54000 [==============================] - 5s 85us/step - loss: 0.4274 - accuracy: 0.8914
Epoch 2/15
54000/54000 [=======

54000/54000 [==============================] - 5s 84us/step - loss: 0.0308 - accuracy: 0.9930
Epoch 14/20
54000/54000 [==============================] - 5s 85us/step - loss: 0.0269 - accuracy: 0.9938
Epoch 15/20
54000/54000 [==============================] - 5s 84us/step - loss: 0.0228 - accuracy: 0.9952
Epoch 16/20
54000/54000 [==============================] - 5s 85us/step - loss: 0.0200 - accuracy: 0.9961 0s - loss:
Epoch 17/20
54000/54000 [==============================] - 5s 85us/step - loss: 0.0172 - accuracy: 0.9967
Epoch 18/20
54000/54000 [==============================] - 5s 85us/step - loss: 0.0149 - accuracy: 0.9975
Epoch 19/20
54000/54000 [==============================] - 5s 85us/step - loss: 0.0126 - accuracy: 0.9980
Epoch 20/20
54000/54000 [==============================] - 5s 84us/step - loss: 0.0108 - accuracy: 0.9984
Epoch 1/20
54000/54000 [==============================] - 5s 84us/step - loss: 0.4381 - accuracy: 0.8871
Epoch 2/20
54000/54000 [========================

54000/54000 [==============================] - 5s 83us/step - loss: 0.0552 - accuracy: 0.9849
Epoch 10/20
54000/54000 [==============================] - 5s 84us/step - loss: 0.0472 - accuracy: 0.9878 0s - loss: 0.0470 - accu
Epoch 11/20
54000/54000 [==============================] - 4s 83us/step - loss: 0.0411 - accuracy: 0.9897 0s - loss: 0.0411 - accuracy: 
Epoch 12/20
54000/54000 [==============================] - 5s 84us/step - loss: 0.0359 - accuracy: 0.9911
Epoch 13/20
54000/54000 [==============================] - 5s 84us/step - loss: 0.0308 - accuracy: 0.9929
Epoch 14/20
54000/54000 [==============================] - 5s 84us/step - loss: 0.0265 - accuracy: 0.9940
Epoch 15/20
54000/54000 [==============================] - 5s 84us/step - loss: 0.0228 - accuracy: 0.9951
Epoch 16/20
54000/54000 [==============================] - 5s 84us/step - loss: 0.0196 - accuracy: 0.9964
Epoch 17/20
54000/54000 [==============================] - 5s 85us/step - loss: 0.0163 - accuracy: 0.9972 1s

54000/54000 [==============================] - 4s 80us/step - loss: 0.1516 - accuracy: 0.9566
Epoch 5/10
54000/54000 [==============================] - 3s 63us/step - loss: 0.1265 - accuracy: 0.9644 1s - los - ETA: 0s - l
Epoch 6/10
54000/54000 [==============================] - 3s 57us/step - loss: 0.1081 - accuracy: 0.9694 0s - loss: 0.1058 - accuracy: 0.97 - ETA: 0s
Epoch 7/10
54000/54000 [==============================] - 3s 58us/step - loss: 0.0934 - accuracy: 0.9734
Epoch 8/10
54000/54000 [==============================] - 3s 57us/step - loss: 0.0810 - accuracy: 0.9773
Epoch 9/10
54000/54000 [==============================] - 3s 56us/step - loss: 0.0709 - accuracy: 0.9803 1s - loss: 0.0714 
Epoch 10/10
54000/54000 [==============================] - 3s 56us/step - loss: 0.0628 - accuracy: 0.9830
Epoch 1/10
54000/54000 [==============================] - 3s 58us/step - loss: 0.4991 - accuracy: 0.8756
Epoch 2/10
54000/54000 [==============================] - 3s 55us/step - loss: 0.23

54000/54000 [==============================] - 3s 65us/step - loss: 0.0684 - accuracy: 0.9814
Epoch 10/10
54000/54000 [==============================] - 3s 56us/step - loss: 0.0603 - accuracy: 0.9838
Epoch 1/10
54000/54000 [==============================] - 3s 59us/step - loss: 0.4917 - accuracy: 0.8768
Epoch 2/10
54000/54000 [==============================] - 3s 57us/step - loss: 0.2334 - accuracy: 0.9334
Epoch 3/10
54000/54000 [==============================] - 3s 56us/step - loss: 0.1799 - accuracy: 0.9488 
Epoch 4/10
54000/54000 [==============================] - 3s 56us/step - loss: 0.1471 - accuracy: 0.9580
Epoch 5/10
54000/54000 [==============================] - 3s 57us/step - loss: 0.1238 - accuracy: 0.9650
Epoch 6/10
54000/54000 [==============================] - 3s 56us/step - loss: 0.1056 - accuracy: 0.9703 0s - loss: 0.1053 - accuracy: 0.
Epoch 7/10
54000/54000 [==============================] - 3s 56us/step - loss: 0.0915 - accuracy: 0.9739
Epoch 8/10
54000/54000 [=======

54000/54000 [==============================] - 3s 56us/step - loss: 0.0690 - accuracy: 0.9811
Epoch 10/15
54000/54000 [==============================] - 3s 56us/step - loss: 0.0605 - accuracy: 0.9840
Epoch 11/15
54000/54000 [==============================] - 3s 55us/step - loss: 0.0536 - accuracy: 0.9857
Epoch 12/15
54000/54000 [==============================] - 3s 56us/step - loss: 0.0470 - accuracy: 0.9877
Epoch 13/15
54000/54000 [==============================] - 3s 55us/step - loss: 0.0412 - accuracy: 0.9900
Epoch 14/15
54000/54000 [==============================] - 3s 56us/step - loss: 0.0366 - accuracy: 0.9914
Epoch 15/15
54000/54000 [==============================] - 3s 55us/step - loss: 0.0323 - accuracy: 0.9928
Epoch 1/15
54000/54000 [==============================] - 3s 57us/step - loss: 0.4847 - accuracy: 0.8799
Epoch 2/15
54000/54000 [==============================] - 3s 55us/step - loss: 0.2341 - accuracy: 0.9341
Epoch 3/15
54000/54000 [==============================] - 3s

54000/54000 [==============================] - 3s 63us/step - loss: 0.0679 - accuracy: 0.9814
Epoch 10/15
54000/54000 [==============================] - 3s 61us/step - loss: 0.0598 - accuracy: 0.9840
Epoch 11/15
54000/54000 [==============================] - 3s 59us/step - loss: 0.0530 - accuracy: 0.9860
Epoch 12/15
54000/54000 [==============================] - 3s 57us/step - loss: 0.0467 - accuracy: 0.9879
Epoch 13/15
54000/54000 [==============================] - 3s 57us/step - loss: 0.0410 - accuracy: 0.9895
Epoch 14/15
54000/54000 [==============================] - 3s 57us/step - loss: 0.0368 - accuracy: 0.9909
Epoch 15/15
54000/54000 [==============================] - 3s 56us/step - loss: 0.0322 - accuracy: 0.9926
Epoch 1/15
54000/54000 [==============================] - 3s 63us/step - loss: 0.4981 - accuracy: 0.8769
Epoch 2/15
54000/54000 [==============================] - 3s 60us/step - loss: 0.2406 - accuracy: 0.9313
Epoch 3/15
54000/54000 [==============================] - 3s

54000/54000 [==============================] - 3s 55us/step - loss: 0.0297 - accuracy: 0.9931
Epoch 17/20
54000/54000 [==============================] - 4s 74us/step - loss: 0.0263 - accuracy: 0.9942
Epoch 18/20
54000/54000 [==============================] - 4s 70us/step - loss: 0.0234 - accuracy: 0.9954 0s - loss: 0.0229 - accuracy: 0.99 - ETA: 0s - loss: 0.022
Epoch 19/20
54000/54000 [==============================] - 3s 59us/step - loss: 0.0206 - accuracy: 0.9961
Epoch 20/20
54000/54000 [==============================] - 3s 60us/step - loss: 0.0179 - accuracy: 0.9969
Epoch 1/20
54000/54000 [==============================] - 3s 63us/step - loss: 0.4932 - accuracy: 0.8823
Epoch 2/20
54000/54000 [==============================] - 3s 61us/step - loss: 0.2371 - accuracy: 0.9327
Epoch 3/20
54000/54000 [==============================] - 3s 60us/step - loss: 0.1838 - accuracy: 0.9482
Epoch 4/20
54000/54000 [==============================] - 3s 61us/step - loss: 0.1503 - accuracy: 0.9568
Epo

54000/54000 [==============================] - 3s 54us/step - loss: 0.0542 - accuracy: 0.9855
Epoch 12/20
54000/54000 [==============================] - 3s 54us/step - loss: 0.0476 - accuracy: 0.9876
Epoch 13/20
54000/54000 [==============================] - 3s 54us/step - loss: 0.0424 - accuracy: 0.9891
Epoch 14/20
54000/54000 [==============================] - 3s 54us/step - loss: 0.0375 - accuracy: 0.9910
Epoch 15/20
54000/54000 [==============================] - 3s 54us/step - loss: 0.0330 - accuracy: 0.9923
Epoch 16/20
54000/54000 [==============================] - 3s 54us/step - loss: 0.0295 - accuracy: 0.9934 0s - loss: 0.0293 - accuracy: 0. - ETA: 0s - loss: 0.0294 - ac
Epoch 17/20
54000/54000 [==============================] - 3s 54us/step - loss: 0.0260 - accuracy: 0.9945
Epoch 18/20
54000/54000 [==============================] - 3s 54us/step - loss: 0.0227 - accuracy: 0.9960
Epoch 19/20
54000/54000 [==============================] - 3s 54us/step - loss: 0.0198 - accuracy: 0.

54000/54000 [==============================] - 2s 33us/step - loss: 0.1256 - accuracy: 0.9636
Epoch 8/10
54000/54000 [==============================] - 2s 33us/step - loss: 0.1115 - accuracy: 0.9681
Epoch 9/10
54000/54000 [==============================] - 2s 33us/step - loss: 0.1003 - accuracy: 0.9715
Epoch 10/10
54000/54000 [==============================] - 2s 33us/step - loss: 0.0899 - accuracy: 0.9749 0s - loss: 0.088 - ETA: 0s - loss: 0.0884 - ac
Epoch 1/10
54000/54000 [==============================] - 2s 35us/step - loss: 0.6128 - accuracy: 0.8595
Epoch 2/10
54000/54000 [==============================] - 2s 33us/step - loss: 0.2773 - accuracy: 0.9228
Epoch 3/10
54000/54000 [==============================] - 2s 33us/step - loss: 0.2210 - accuracy: 0.9382
Epoch 4/10
54000/54000 [==============================] - 2s 33us/step - loss: 0.1871 - accuracy: 0.9472
Epoch 5/10
54000/54000 [==============================] - 2s 33us/step - loss: 0.1622 - accuracy: 0.9538
Epoch 6/10
54000/5

54000/54000 [==============================] - 2s 32us/step - loss: 0.0895 - accuracy: 0.9749
Epoch 1/10
54000/54000 [==============================] - 2s 34us/step - loss: 0.6133 - accuracy: 0.8562
Epoch 2/10
54000/54000 [==============================] - 2s 32us/step - loss: 0.2752 - accuracy: 0.9237
Epoch 3/10
54000/54000 [==============================] - 2s 32us/step - loss: 0.2180 - accuracy: 0.9379
Epoch 4/10
54000/54000 [==============================] - 2s 32us/step - loss: 0.1836 - accuracy: 0.9482
Epoch 5/10
54000/54000 [==============================] - 2s 32us/step - loss: 0.1589 - accuracy: 0.9553 1s - loss: 0.1657  - ETA: 0s
Epoch 6/10
54000/54000 [==============================] - 2s 32us/step - loss: 0.1394 - accuracy: 0.9604
Epoch 7/10
54000/54000 [==============================] - 2s 32us/step - loss: 0.1236 - accuracy: 0.9654
Epoch 8/10
54000/54000 [==============================] - 2s 32us/step - loss: 0.1099 - accuracy: 0.9693ETA: 0s - loss: 0.1106 - 
Epoch 9/10
5

Epoch 10/15
54000/54000 [==============================] - 2s 33us/step - loss: 0.0873 - accuracy: 0.9754 
Epoch 11/15
54000/54000 [==============================] - 2s 33us/step - loss: 0.0785 - accuracy: 0.9791 0s - l
Epoch 12/15
54000/54000 [==============================] - 2s 32us/step - loss: 0.0711 - accuracy: 0.9809
Epoch 13/15
54000/54000 [==============================] - 2s 33us/step - loss: 0.0646 - accuracy: 0.9833
Epoch 14/15
54000/54000 [==============================] - 2s 32us/step - loss: 0.0585 - accuracy: 0.9846
Epoch 15/15
54000/54000 [==============================] - 2s 33us/step - loss: 0.0535 - accuracy: 0.9863
Epoch 1/15
54000/54000 [==============================] - 2s 34us/step - loss: 0.6098 - accuracy: 0.8544
Epoch 2/15
54000/54000 [==============================] - 2s 32us/step - loss: 0.2811 - accuracy: 0.9215
Epoch 3/15
54000/54000 [==============================] - 2s 32us/step - loss: 0.2223 - accuracy: 0.9380
Epoch 4/15
54000/54000 [=================

54000/54000 [==============================] - 2s 33us/step - loss: 0.0918 - accuracy: 0.9746  - ETA: 0s - loss: 0.0918 - accuracy
Epoch 11/15
54000/54000 [==============================] - 2s 32us/step - loss: 0.0831 - accuracy: 0.9773
Epoch 12/15
54000/54000 [==============================] - 2s 32us/step - loss: 0.0757 - accuracy: 0.9794 0s - loss: 0.0762 - accuracy
Epoch 13/15
54000/54000 [==============================] - 2s 32us/step - loss: 0.0686 - accuracy: 0.9816
Epoch 14/15
54000/54000 [==============================] - 2s 32us/step - loss: 0.0627 - accuracy: 0.9831 0s - los
Epoch 15/15
54000/54000 [==============================] - 2s 32us/step - loss: 0.0571 - accuracy: 0.9847 0s - loss: 0 - ETA: 0s - loss: 0.0568 - accu
Epoch 1/15
54000/54000 [==============================] - 2s 35us/step - loss: 0.6219 - accuracy: 0.8515
Epoch 2/15
54000/54000 [==============================] - 2s 33us/step - loss: 0.2839 - accuracy: 0.9204
Epoch 3/15
54000/54000 [======================

Epoch 10/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.0901 - accuracy: 0.9756
Epoch 11/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.0814 - accuracy: 0.9778
Epoch 12/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.0741 - accuracy: 0.9800
Epoch 13/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.0672 - accuracy: 0.9822 1s - loss: 0.0690 - accuracy: 0. - ETA: 1s - loss: 0.0678 - accuracy: 0. - E
Epoch 14/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.0614 - accuracy: 0.9841 0s - loss:
Epoch 15/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.0560 - accuracy: 0.9853 0s - loss: 0.0558 - accuracy
Epoch 16/20
54000/54000 [==============================] - 2s 32us/step - loss: 0.0510 - accuracy: 0.9873
Epoch 17/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.0465 - accuracy: 0.9885
Epoch 18/20
54000/54000 [==========

54000/54000 [==============================] - 2s 34us/step - loss: 0.1846 - accuracy: 0.9477
Epoch 5/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.1597 - accuracy: 0.9554
Epoch 6/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.1396 - accuracy: 0.9613
Epoch 7/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.1236 - accuracy: 0.9656
Epoch 8/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.1109 - accuracy: 0.9686
Epoch 9/20
54000/54000 [==============================] - 2s 36us/step - loss: 0.0996 - accuracy: 0.9726
Epoch 10/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.0895 - accuracy: 0.9748
Epoch 11/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.0809 - accuracy: 0.9778
Epoch 12/20
54000/54000 [==============================] - 2s 33us/step - loss: 0.0733 - accuracy: 0.9799
Epoch 13/20
54000/54000 [==============================] - 2s 3

54000/54000 [==============================] - 2s 33us/step - loss: 0.0385 - accuracy: 0.9909
Epoch 20/20
54000/54000 [==============================] - 2s 32us/step - loss: 0.0350 - accuracy: 0.9920
Epoch 1/20
60000/60000 [==============================] - 3s 56us/step - loss: 0.4676 - accuracy: 0.8834
Epoch 2/20
60000/60000 [==============================] - 3s 55us/step - loss: 0.2237 - accuracy: 0.9367
Epoch 3/20
60000/60000 [==============================] - 3s 55us/step - loss: 0.1712 - accuracy: 0.9509
Epoch 4/20
60000/60000 [==============================] - 3s 55us/step - loss: 0.1382 - accuracy: 0.9606
Epoch 5/20
60000/60000 [==============================] - 3s 55us/step - loss: 0.1150 - accuracy: 0.9670
Epoch 6/20
60000/60000 [==============================] - 3s 55us/step - loss: 0.0975 - accuracy: 0.9728
Epoch 7/20
60000/60000 [==============================] - 3s 55us/step - loss: 0.0837 - accuracy: 0.9770
Epoch 8/20
60000/60000 [==============================] - 3s 55us

In [13]:
#PartH
#run this after getting all grid results.
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
score = grid.best_estimator_.model.evaluate(X_test, Y_test)
print("Score: " + str(score[1]))


Best: -0.088852 using {'epochs': 20, 'batch_size': 50}
10000/10000 [==============================] - 0s 39us/step
Score: 0.977500021458


In [ ]:
#PartH
#run this after getting all grid results.
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
score = grid.best_estimator_.model.evaluate(X_test, Y_test)
print("Score: " + str(score[1]))



In [ ]:
#took 1hour and 20min to run.
